### ISSUE TITLE
Upgrade to jQuery 3.5.0

### ISSUE THREAD

**Issue by brianhjelle** [emberjs/ember-jquery#265]
There is a security vulnerability in jquery 3.4.1 which has been fixed in 3.5.0 as of April 10, 2020.
[jQuery Blog](https://blog.jquery.com/)

**Comment by sharpshark28** [comment]
I believe simply merging #264 and publishing a release would resolve this. This should likely be a priority item @rwjblue @simonihmig.

**Comment by Turbo87** [comment]
this package specifies `"jquery": "^3.4.1"`, which means that any version above or equal to `3.4.1` is compatible, which includes the v3.5.0 release with the security fix. if you `yarn install` or `npm install` this package now you will automatically get the v3.5.0 release because of semver.

if you have an existing app with `@ember/jquery` then you may have to renew your lockfile to update to the new jQuery version.

in short: releasing a new `@ember/jquery` version is not strictly necessary to fix the issue, but I agree that it still might be a good idea if someone has time to work on that

**Comment by Turbo87** [comment]
also, merging https://github.com/emberjs/ember-jquery/pull/264 is currently blocked because CI is failing. it looks like CI is failing because some transient dependency has dropped support for Node 8 without releasing that as a major version release 🙄 

in other words: we would need to drop support for Node 8 here too to fix CI, which is a breaking change and would require a new major version release.

**Comment by mileslane** [comment]
GHSA-jpcq-cgw6-v4j6
moderate severity
Vulnerable versions: >= 1.0.3, < 3.5.0
Patched version: 3.5.0
Impact
Passing HTML containing <option> elements from untrusted sources - even after sanitizing them - to one of jQuery's DOM manipulation methods (i.e. .html(), .append(), and others) may execute untrusted code.

Patches
This problem is patched in jQuery 3.5.0.

Workarounds
To workaround this issue without upgrading, use DOMPurify with its SAFE_FOR_JQUERY option to sanitize the HTML string before passing it to a jQuery method.

References
https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

For more information
If you have any questions or comments about this advisory, search for a relevant issue in the jQuery repo. If you don't find an answer, open a new issue.

GHSA-gxr4-xjj5-5px2
moderate severity
Vulnerable versions: >= 1.2, < 3.5.0
Patched version: 3.5.0
Impact
Passing HTML from untrusted sources - even after sanitizing it - to one of jQuery's DOM manipulation methods (i.e. .html(), .append(), and others) may execute untrusted code.

Patches
This problem is patched in jQuery 3.5.0.

Workarounds
To workaround the issue without upgrading, adding the following to your code:

jQuery.htmlPrefilter = function( html ) {
	return html;
};
You need to use at least jQuery 1.12/2.2 or newer to be able to apply this workaround.

References
https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/
https://jquery.com/upgrade-guide/3.5/

**Comment by rwjblue** [comment]
As mentioned above, this package already allows using a safe version. A change here is **not** required.

**Comment by mixonic** [comment]
Closing this as https://github.com/emberjs/ember-jquery/pull/264 is already merged and as mentioned elsewhere the dependency floats and should not block per-app adoption of newer jQuery minor releases.

Please re-open if we have missed anything!
